[theme]
primaryColor="#3B82F6"
backgroundColor="#0f172a"
secondaryBackgroundColor="#1e293b"
textColor="#ffffff"
font="sans serif"

[server]
runOnSave=true
[server]
maxUploadSize = 500  # 최대 500MB까지 가능